// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWZ1HMAgrvRi47H9s5_h7xuWoQNwxt4mg',
    appId: '1:7441741820:web:284e70fba8e903a7a7e479',
    messagingSenderId: '7441741820',
    projectId: 'spinnergame-90440',
    authDomain: 'spinnergame-90440.firebaseapp.com',
    storageBucket: 'spinnergame-90440.appspot.com',
    measurementId: 'G-0FJV9CG16K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQIppbx_s0yHBjA1Ums7zPkxLfcnfmD6s',
    appId: '1:7441741820:android:5d936e2109e375cfa7e479',
    messagingSenderId: '7441741820',
    projectId: 'spinnergame-90440',
    storageBucket: 'spinnergame-90440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn7O5UQ66R_Sw7CxMirQw7xSdoHo_RjX4',
    appId: '1:7441741820:ios:1b81c89a5190507ea7e479',
    messagingSenderId: '7441741820',
    projectId: 'spinnergame-90440',
    storageBucket: 'spinnergame-90440.appspot.com',
    iosClientId: '7441741820-jkbt75ub48e4ip3ek3bki5dss3kl1gqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn7O5UQ66R_Sw7CxMirQw7xSdoHo_RjX4',
    appId: '1:7441741820:ios:1b81c89a5190507ea7e479',
    messagingSenderId: '7441741820',
    projectId: 'spinnergame-90440',
    storageBucket: 'spinnergame-90440.appspot.com',
    iosClientId: '7441741820-jkbt75ub48e4ip3ek3bki5dss3kl1gqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWZ1HMAgrvRi47H9s5_h7xuWoQNwxt4mg',
    appId: '1:7441741820:web:1aa81e7301b3eaf7a7e479',
    messagingSenderId: '7441741820',
    projectId: 'spinnergame-90440',
    authDomain: 'spinnergame-90440.firebaseapp.com',
    storageBucket: 'spinnergame-90440.appspot.com',
    measurementId: 'G-VD66LS21FT',
  );
}
